// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';
import {model} from '../models';
import {amodel} from '../models';
import {db} from '../models';
import {backend} from '../models';
import {assistcli} from '../models';
import {flow} from '../models';
import {ebmodel} from '../models';
import {externaltoken} from '../models';
import {system} from '../models';
import {dhcpd} from '../models';
import {rumodel} from '../models';
import {networking} from '../models';
import {datelib} from '../models';
import {store} from '../models';
import {node} from '../models';
import {nodes} from '../models';
import {flowcli} from '../models';

export function AddConnection(arg1:storage.RubixConnection):Promise<storage.RubixConnection>;

export function AddConsumer(arg1:string,arg2:string,arg3:model.Consumer):Promise<model.Consumer>;

export function AddDevice(arg1:string,arg2:string,arg3:model.Device):Promise<model.Device>;

export function AddDevicesBulk(arg1:string,arg2:string,arg3:Array<model.Device>):Promise<void>;

export function AddFlowNetwork(arg1:string,arg2:string,arg3:model.FlowNetwork):Promise<model.FlowNetwork>;

export function AddHost(arg1:string,arg2:amodel.Host):Promise<amodel.Host>;

export function AddHostNetwork(arg1:string,arg2:amodel.Network):Promise<amodel.Network>;

export function AddLocation(arg1:string,arg2:amodel.Location):Promise<amodel.Location>;

export function AddNetwork(arg1:string,arg2:string,arg3:model.Network):Promise<model.Network>;

export function AddPoint(arg1:string,arg2:string,arg3:model.Point):Promise<model.Point>;

export function AddPointsBulk(arg1:string,arg2:string,arg3:Array<model.Point>):Promise<void>;

export function AddProducer(arg1:string,arg2:string,arg3:model.Producer):Promise<model.Producer>;

export function AddStream(arg1:string,arg2:string,arg3:string,arg4:model.Stream):Promise<model.Stream>;

export function AddWiresConnection(arg1:string,arg2:string,arg3:boolean,arg4:db.Connection):Promise<db.Connection>;

export function BacnetWhois(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<model.Device>>;

export function BulkDeleteWiresConnection(arg1:string,arg2:string,arg3:boolean,arg4:Array<string>):Promise<any>;

export function CreateWriter(arg1:string,arg2:string,arg3:model.Writer):Promise<model.Writer>;

export function DeleteAllConnections():Promise<backend.DeleteAllConnections>;

export function DeleteBackup(arg1:string):Promise<string>;

export function DeleteBackupBulk(arg1:Array<backend.UUIDs>):Promise<any>;

export function DeleteConnection(arg1:string):Promise<string>;

export function DeleteConnectionBulk(arg1:Array<backend.UUIDs>):Promise<any>;

export function DeleteConsumer(arg1:string,arg2:string,arg3:string):Promise<any>;

export function DeleteConsumerBulk(arg1:string,arg2:string,arg3:Array<backend.UUIDs>):Promise<any>;

export function DeleteDevice(arg1:string,arg2:string,arg3:string):Promise<any>;

export function DeleteDeviceBulk(arg1:string,arg2:string,arg3:Array<backend.UUIDs>):Promise<any>;

export function DeleteFlowNetwork(arg1:string,arg2:string,arg3:string):Promise<any>;

export function DeleteFlowNetworkBulk(arg1:string,arg2:string,arg3:Array<backend.UUIDs>):Promise<any>;

export function DeleteFlowNetworkClone(arg1:string,arg2:string,arg3:string):Promise<any>;

export function DeleteFlowNetworkCloneBulk(arg1:string,arg2:string,arg3:Array<backend.UUIDs>):Promise<any>;

export function DeleteHost(arg1:string,arg2:string):Promise<assistcli.Response>;

export function DeleteHostBulk(arg1:string,arg2:Array<backend.UUIDs>):Promise<any>;

export function DeleteHostNetwork(arg1:string,arg2:string):Promise<assistcli.Response>;

export function DeleteHostNetworkBulk(arg1:string,arg2:Array<backend.UUIDs>):Promise<any>;

export function DeleteLocation(arg1:string,arg2:string):Promise<assistcli.Response>;

export function DeleteLocationBulk(arg1:string,arg2:Array<backend.UUIDs>):Promise<any>;

export function DeleteLogBulk(arg1:Array<backend.UUIDs>):Promise<any>;

export function DeleteNetwork(arg1:string,arg2:string,arg3:string):Promise<any>;

export function DeleteNetworkBulk(arg1:string,arg2:string,arg3:Array<backend.UUIDs>):Promise<any>;

export function DeletePoint(arg1:string,arg2:string,arg3:string):Promise<any>;

export function DeletePointBulk(arg1:string,arg2:string,arg3:Array<backend.UUIDs>):Promise<any>;

export function DeleteProducer(arg1:string,arg2:string,arg3:string):Promise<any>;

export function DeleteProducerBulk(arg1:string,arg2:string,arg3:Array<backend.UUIDs>):Promise<any>;

export function DeleteStream(arg1:string,arg2:string,arg3:string):Promise<any>;

export function DeleteStreamBulk(arg1:string,arg2:string,arg3:Array<backend.UUIDs>):Promise<any>;

export function DeleteStreamBulkClones(arg1:string,arg2:string,arg3:Array<backend.UUIDs>):Promise<any>;

export function DeleteStreamClone(arg1:string,arg2:string,arg3:string):Promise<any>;

export function DeleteWiresConnection(arg1:string,arg2:string,arg3:boolean,arg4:string):Promise<void>;

export function DeleteWriter(arg1:string,arg2:string,arg3:string):Promise<any>;

export function DeleteWriterClone(arg1:string,arg2:string,arg3:string):Promise<any>;

export function DeleteWriterCloneBulk(arg1:string,arg2:string,arg3:Array<backend.UUIDs>):Promise<any>;

export function DeleteWritersBulk(arg1:string,arg2:string,arg3:Array<backend.UUIDs>):Promise<any>;

export function DoBackup(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:any):Promise<storage.Backup>;

export function DownloadFlow(arg1:string,arg2:string,arg3:boolean,arg4:any,arg5:boolean):Promise<flow.Message>;

export function EdgeBiosInstalledRubixEdgeVersion(arg1:string,arg2:string):Promise<ebmodel.Version>;

export function EdgeBiosLogin(arg1:string,arg2:string,arg3:string,arg4:string):Promise<model.TokenResponse>;

export function EdgeBiosRubixEdgeInstall(arg1:string,arg2:string,arg3:string):Promise<any>;

export function EdgeBiosRubixEdgeVersions():Promise<Array<string>>;

export function EdgeBiosToken(arg1:string,arg2:string,arg3:string,arg4:string):Promise<externaltoken.ExternalToken>;

export function EdgeBiosTokenBlock(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<externaltoken.ExternalToken>;

export function EdgeBiosTokenDelete(arg1:string,arg2:string,arg3:string,arg4:string):Promise<boolean>;

export function EdgeBiosTokenGenerate(arg1:string,arg2:string,arg3:string,arg4:string):Promise<externaltoken.ExternalToken>;

export function EdgeBiosTokenRegenerate(arg1:string,arg2:string,arg3:string,arg4:string):Promise<externaltoken.ExternalToken>;

export function EdgeBiosTokens(arg1:string,arg2:string,arg3:string):Promise<externaltoken.ExternalToken>;

export function EdgeDHCPPortExists(arg1:string,arg2:string,arg3:system.NetworkingBody):Promise<system.DHCPPortExists>;

export function EdgeDHCPSetAsAuto(arg1:string,arg2:string,arg3:system.NetworkingBody):Promise<system.Message>;

export function EdgeDHCPSetStaticIP(arg1:string,arg2:string,arg3:dhcpd.SetStaticIP):Promise<string>;

export function EdgeDeviceInfoAndApps(arg1:string,arg2:string):Promise<rumodel.EdgeDeviceInfo>;

export function EdgeEnablePlugins(arg1:string,arg2:string,arg3:Array<string>,arg4:boolean):Promise<rumodel.Response>;

export function EdgeGetConfigPlugin(arg1:string,arg2:string,arg3:string):Promise<rumodel.Response>;

export function EdgeGetNetworks(arg1:string,arg2:string):Promise<Array<networking.NetworkInterfaces>>;

export function EdgeGetPlugins(arg1:string,arg2:string):Promise<rumodel.Response>;

export function EdgeGetPluginsDistribution(arg1:string,arg2:string):Promise<rumodel.Response>;

export function EdgeInstallApp(arg1:string,arg2:string,arg3:string,arg4:string):Promise<rumodel.Response>;

export function EdgeInstallPlugin(arg1:string,arg2:string,arg3:string):Promise<rumodel.Response>;

export function EdgeRestartPlugins(arg1:string,arg2:string,arg3:Array<string>):Promise<rumodel.Response>;

export function EdgeRubixAppVersions(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<Array<string>>;

export function EdgeRubixScan(arg1:string,arg2:string):Promise<any>;

export function EdgeServiceRestart(arg1:string,arg2:string,arg3:string):Promise<amodel.Message>;

export function EdgeServiceStart(arg1:string,arg2:string,arg3:string):Promise<amodel.Message>;

export function EdgeServiceStop(arg1:string,arg2:string,arg3:string):Promise<amodel.Message>;

export function EdgeSystemCtlState(arg1:string,arg2:string,arg3:string):Promise<amodel.AppSystemState>;

export function EdgeUnInstallApp(arg1:string,arg2:string,arg3:string):Promise<amodel.Message>;

export function EdgeUninstallPlugin(arg1:string,arg2:string,arg3:string):Promise<rumodel.Response>;

export function EdgeUpdateConfigPlugin(arg1:string,arg2:string,arg3:string,arg4:string):Promise<rumodel.Response>;

export function EditConsumer(arg1:string,arg2:string,arg3:string,arg4:model.Consumer):Promise<model.Consumer>;

export function EditDevice(arg1:string,arg2:string,arg3:string,arg4:model.Device):Promise<model.Device>;

export function EditFlowNetwork(arg1:string,arg2:string,arg3:string,arg4:model.FlowNetwork):Promise<model.FlowNetwork>;

export function EditHost(arg1:string,arg2:string,arg3:amodel.Host):Promise<amodel.Host>;

export function EditHostNetwork(arg1:string,arg2:string,arg3:amodel.Network):Promise<amodel.Network>;

export function EditNetwork(arg1:string,arg2:string,arg3:string,arg4:model.Network):Promise<model.Network>;

export function EditPoint(arg1:string,arg2:string,arg3:string,arg4:model.Point):Promise<model.Point>;

export function EditProducer(arg1:string,arg2:string,arg3:string,arg4:model.Producer):Promise<model.Producer>;

export function EditStream(arg1:string,arg2:string,arg3:string,arg4:model.Stream):Promise<model.Stream>;

export function EditWriter(arg1:string,arg2:string,arg3:string,arg4:model.Writer,arg5:boolean):Promise<model.Writer>;

export function ExportBackup(arg1:string):Promise<void>;

export function ExportDevicesBulk(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<storage.Backup>;

export function ExportNetworksBulk(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<storage.Backup>;

export function ExportPointBulk(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<storage.Backup>;

export function GetBackup(arg1:string):Promise<storage.Backup>;

export function GetBackups():Promise<Array<storage.Backup>>;

export function GetBackupsByApplication(arg1:string,arg2:string,arg3:boolean):Promise<Array<storage.Backup>>;

export function GetBackupsNoData():Promise<Array<storage.Backup>>;

export function GetBacnetDevicePoints(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:boolean):Promise<Array<model.Point>>;

export function GetConnection(arg1:string):Promise<storage.RubixConnection>;

export function GetConnectionSchema():Promise<backend.ConnectionSchema>;

export function GetConnections():Promise<Array<storage.RubixConnection>>;

export function GetConsumer(arg1:string,arg2:string,arg3:string):Promise<model.Consumer>;

export function GetConsumerClones(arg1:string,arg2:string):Promise<Array<model.Consumer>>;

export function GetConsumers(arg1:string,arg2:string):Promise<Array<model.Consumer>>;

export function GetDevice(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<model.Device>;

export function GetDevices(arg1:string,arg2:string,arg3:boolean):Promise<Array<model.Device>>;

export function GetFlow(arg1:string,arg2:string,arg3:boolean):Promise<any>;

export function GetFlowDeviceSchema(arg1:string,arg2:string,arg3:string):Promise<any>;

export function GetFlowNetwork(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<model.FlowNetwork>;

export function GetFlowNetworkClone(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<model.FlowNetworkClone>;

export function GetFlowNetworkClones(arg1:string,arg2:string,arg3:boolean):Promise<Array<model.FlowNetworkClone>>;

export function GetFlowNetworkSchema(arg1:string,arg2:string,arg3:string):Promise<any>;

export function GetFlowNetworks(arg1:string,arg2:string,arg3:boolean):Promise<Array<model.FlowNetwork>>;

export function GetFlowPointSchema(arg1:string,arg2:string,arg3:string):Promise<any>;

export function GetGitToken(arg1:string,arg2:boolean):Promise<string>;

export function GetHost(arg1:string,arg2:string):Promise<amodel.Host>;

export function GetHostNetwork(arg1:string,arg2:string):Promise<amodel.Network>;

export function GetHostNetworks(arg1:string):Promise<Array<amodel.Network>>;

export function GetHostSchema(arg1:string):Promise<amodel.HostSchema>;

export function GetHostTime(arg1:string,arg2:string):Promise<any>;

export function GetHosts(arg1:string):Promise<Array<amodel.Host>>;

export function GetLocalStorage(arg1:string,arg2:string):Promise<model.LocalStorageFlowNetwork>;

export function GetLocation(arg1:string,arg2:string):Promise<amodel.Location>;

export function GetLocationSchema(arg1:string):Promise<any>;

export function GetLocationTableSchema(arg1:string):Promise<any>;

export function GetLocations(arg1:string):Promise<Array<amodel.Location>>;

export function GetLogs():Promise<any>;

export function GetLogsByConnection(arg1:string):Promise<any>;

export function GetLogsWithData():Promise<any>;

export function GetNetwork(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<model.Network>;

export function GetNetworkBackupsByPlugin(arg1:string,arg2:string,arg3:string):Promise<Array<storage.Backup>>;

export function GetNetworkBackupsByUUID(arg1:string,arg2:string,arg3:string):Promise<Array<storage.Backup>>;

export function GetNetworkByPluginName(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<model.Network>;

export function GetNetworkDevices(arg1:string,arg2:string,arg3:string):Promise<Array<model.Device>>;

export function GetNetworkSchema(arg1:string):Promise<any>;

export function GetNetworkWithPoints(arg1:string,arg2:string,arg3:string):Promise<model.Network>;

export function GetNetworks(arg1:string,arg2:string,arg3:boolean):Promise<Array<model.Network>>;

export function GetNetworksWithPoints(arg1:string,arg2:string):Promise<Array<model.Network>>;

export function GetNetworksWithPointsDisplay(arg1:string,arg2:string):Promise<Array<backend.NetworksList>>;

export function GetPcGetNetworks():Promise<any>;

export function GetPcGetNetworksSchema():Promise<any>;

export function GetPcInterfaces():Promise<networking.InterfaceNames>;

export function GetPcTime():Promise<datelib.Time>;

export function GetPoint(arg1:string,arg2:string,arg3:string):Promise<model.Point>;

export function GetPoints(arg1:string,arg2:string):Promise<Array<model.Point>>;

export function GetPointsForDevice(arg1:string,arg2:string,arg3:string):Promise<Array<model.Point>>;

export function GetProducer(arg1:string,arg2:string,arg3:string):Promise<model.Producer>;

export function GetProducerClones(arg1:string,arg2:string):Promise<Array<model.Producer>>;

export function GetProducers(arg1:string,arg2:string):Promise<Array<model.Producer>>;

export function GetRcNetworkSchema(arg1:string,arg2:string):Promise<any>;

export function GetRelease(arg1:string):Promise<store.Release>;

export function GetReleases():Promise<Array<store.Release>>;

export function GetScannerSchema():Promise<any>;

export function GetSchedules(arg1:string,arg2:string):Promise<any>;

export function GetServerNetworking(arg1:string):Promise<any>;

export function GetServerTime(arg1:string):Promise<any>;

export function GetSetting(arg1:string):Promise<storage.Settings>;

export function GetStream(arg1:string,arg2:string,arg3:string):Promise<model.Stream>;

export function GetStreamClones(arg1:string,arg2:string):Promise<Array<model.StreamClone>>;

export function GetStreams(arg1:string,arg2:string):Promise<Array<model.Stream>>;

export function GetStreamsByFlowNetwork(arg1:string,arg2:string,arg3:string):Promise<Array<model.Stream>>;

export function GetWiresConnection(arg1:string,arg2:string,arg3:boolean,arg4:string):Promise<db.Connection>;

export function GetWiresConnections(arg1:string,arg2:string,arg3:boolean):Promise<Array<db.Connection>>;

export function GetWriterClones(arg1:string,arg2:string):Promise<Array<model.WriterClone>>;

export function GetWriters(arg1:string,arg2:string):Promise<Array<model.Writer>>;

export function GitDownloadRelease(arg1:string,arg2:string):Promise<store.Release>;

export function GitDownloadReleases():Promise<rumodel.Response>;

export function GitListReleases(arg1:string):Promise<Array<store.ReleaseList>>;

export function ImportBackup(arg1:storage.Backup):Promise<string>;

export function ImportDevicesBulk(arg1:string,arg2:string,arg3:string,arg4:string):Promise<backend.BulkAddResponse>;

export function ImportNetworksBulk(arg1:string,arg2:string,arg3:string):Promise<backend.BulkAddResponse>;

export function ImportPointBulk(arg1:string,arg2:string,arg3:string,arg4:string):Promise<backend.BulkAddResponse>;

export function NodeHelp(arg1:string,arg2:string,arg3:boolean):Promise<Array<node.Help>>;

export function NodeHelpByName(arg1:string,arg2:string,arg3:boolean,arg4:string):Promise<node.Help>;

export function NodePallet(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<Array<nodes.PalletNode>>;

export function NodePayload(arg1:string,arg2:string,arg3:boolean,arg4:any,arg5:string):Promise<flow.Message>;

export function NodeSchema(arg1:string,arg2:string,arg3:boolean,arg4:string):Promise<flowcli.Schema>;

export function NodeValue(arg1:string,arg2:string,arg3:boolean,arg4:string):Promise<node.Values>;

export function NodeValues(arg1:string,arg2:string,arg3:boolean):Promise<Array<node.Values>>;

export function NubeHelp():Promise<void>;

export function OnQuit():Promise<void>;

export function OnReload():Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function PingHost(arg1:string,arg2:string):Promise<boolean>;

export function PingRubixAssist(arg1:string):Promise<boolean>;

export function RcSetNetworks(arg1:string,arg2:string,arg3:backend.RcNetworkBody):Promise<void>;

export function RubixAssistLogin(arg1:string,arg2:string,arg3:string):Promise<model.TokenResponse>;

export function RubixAssistToken(arg1:string,arg2:string,arg3:string):Promise<externaltoken.ExternalToken>;

export function RubixAssistTokenBlock(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<externaltoken.ExternalToken>;

export function RubixAssistTokenDelete(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function RubixAssistTokenGenerate(arg1:string,arg2:string,arg3:string):Promise<externaltoken.ExternalToken>;

export function RubixAssistTokenRegenerate(arg1:string,arg2:string,arg3:string):Promise<externaltoken.ExternalToken>;

export function RubixAssistTokens(arg1:string,arg2:string):Promise<externaltoken.ExternalToken>;

export function Scanner(arg1:string,arg2:string,arg3:number,arg4:Array<string>):Promise<any>;

export function StoreDownloadApp(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<store.InstallResponse>;

export function UpdateConnection(arg1:string,arg2:storage.RubixConnection):Promise<storage.RubixConnection>;

export function UpdateLocalStorage(arg1:string,arg2:string,arg3:model.LocalStorageFlowNetwork):Promise<model.LocalStorageFlowNetwork>;

export function UpdateLocation(arg1:string,arg2:string,arg3:amodel.Location):Promise<amodel.Location>;

export function UpdateSettings(arg1:string,arg2:storage.Settings):Promise<storage.Settings>;

export function UpdateWiresConnection(arg1:string,arg2:string,arg3:boolean,arg4:string,arg5:db.Connection):Promise<db.Connection>;

export function WiresBackup(arg1:string,arg2:string,arg3:string):Promise<storage.Backup>;

export function WiresBackupRestore(arg1:string,arg2:string,arg3:string):Promise<any>;

export function WritePointValue(arg1:string,arg2:string,arg3:string,arg4:model.Priority):Promise<model.Point>;
