// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetPcGetNetworksSchema() {
  return window['go']['main']['App']['GetPcGetNetworksSchema']();
}

export function DeleteNetwork(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteNetwork'](arg1, arg2, arg3);
}

export function GetBackupsByApplication(arg1, arg2) {
  return window['go']['main']['App']['GetBackupsByApplication'](arg1, arg2);
}

export function GetLocations(arg1) {
  return window['go']['main']['App']['GetLocations'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function AddDevice(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddDevice'](arg1, arg2, arg3);
}

export function AddHostNetwork(arg1, arg2) {
  return window['go']['main']['App']['AddHostNetwork'](arg1, arg2);
}

export function AddNetwork(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddNetwork'](arg1, arg2, arg3);
}

export function EditPoint(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EditPoint'](arg1, arg2, arg3, arg4);
}

export function GetHostTime(arg1, arg2) {
  return window['go']['main']['App']['GetHostTime'](arg1, arg2);
}

export function GetNetworkSchema(arg1) {
  return window['go']['main']['App']['GetNetworkSchema'](arg1);
}

export function DeleteHostNetwork(arg1, arg2) {
  return window['go']['main']['App']['DeleteHostNetwork'](arg1, arg2);
}

export function DeleteLocation(arg1, arg2) {
  return window['go']['main']['App']['DeleteLocation'](arg1, arg2);
}

export function DisablePlugin(arg1, arg2, arg3) {
  return window['go']['main']['App']['DisablePlugin'](arg1, arg2, arg3);
}

export function GetScannerSchema() {
  return window['go']['main']['App']['GetScannerSchema']();
}

export function GetServerNetworking(arg1) {
  return window['go']['main']['App']['GetServerNetworking'](arg1);
}

export function HostRubixScan(arg1, arg2) {
  return window['go']['main']['App']['HostRubixScan'](arg1, arg2);
}

export function Scanner(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Scanner'](arg1, arg2, arg3, arg4);
}

export function UpdateLocation(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateLocation'](arg1, arg2, arg3);
}

export function DeleteAllConnections() {
  return window['go']['main']['App']['DeleteAllConnections']();
}

export function GetHosts(arg1) {
  return window['go']['main']['App']['GetHosts'](arg1);
}

export function GetNetworks(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetNetworks'](arg1, arg2, arg3);
}

export function WiresBackupRestore(arg1, arg2, arg3) {
  return window['go']['main']['App']['WiresBackupRestore'](arg1, arg2, arg3);
}

export function DeletePoint(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeletePoint'](arg1, arg2, arg3);
}

export function GetLogsWithData() {
  return window['go']['main']['App']['GetLogsWithData']();
}

export function OpenURL(arg1) {
  window['go']['main']['App']['OpenURL'](arg1);
}

export function GetPcInterfaces() {
  return window['go']['main']['App']['GetPcInterfaces']();
}

export function UpdateConnection(arg1, arg2) {
  return window['go']['main']['App']['UpdateConnection'](arg1, arg2);
}

export function WiresBackup(arg1, arg2) {
  return window['go']['main']['App']['WiresBackup'](arg1, arg2);
}

export function GetBackups() {
  return window['go']['main']['App']['GetBackups']();
}

export function GetHostInterfaces(arg1, arg2) {
  return window['go']['main']['App']['GetHostInterfaces'](arg1, arg2);
}

export function GetHostInternetIP(arg1, arg2) {
  return window['go']['main']['App']['GetHostInternetIP'](arg1, arg2);
}

export function AddHost(arg1, arg2) {
  return window['go']['main']['App']['AddHost'](arg1, arg2);
}

export function DeleteBackup(arg1) {
  return window['go']['main']['App']['DeleteBackup'](arg1);
}

export function PingHost(arg1, arg2) {
  return window['go']['main']['App']['PingHost'](arg1, arg2);
}

export function GetNetworksWithPoints(arg1, arg2) {
  return window['go']['main']['App']['GetNetworksWithPoints'](arg1, arg2);
}

export function GetPoint(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetPoint'](arg1, arg2, arg3);
}

export function AddPoint(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddPoint'](arg1, arg2, arg3);
}

export function EditDevice(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EditDevice'](arg1, arg2, arg3, arg4);
}

export function EditHost(arg1, arg2, arg3) {
  return window['go']['main']['App']['EditHost'](arg1, arg2, arg3);
}

export function AddLocation(arg1, arg2) {
  return window['go']['main']['App']['AddLocation'](arg1, arg2);
}

export function GetConnections() {
  return window['go']['main']['App']['GetConnections']();
}

export function GetDevices(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetDevices'](arg1, arg2, arg3);
}

export function GetLocation(arg1, arg2) {
  return window['go']['main']['App']['GetLocation'](arg1, arg2);
}

export function GetNetwork(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetNetwork'](arg1, arg2, arg3, arg4);
}

export function GetServerTime(arg1) {
  return window['go']['main']['App']['GetServerTime'](arg1);
}

export function EnablePlugin(arg1, arg2, arg3) {
  return window['go']['main']['App']['EnablePlugin'](arg1, arg2, arg3);
}

export function GetDevice(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetDevice'](arg1, arg2, arg3, arg4);
}

export function GetHostSchema(arg1) {
  return window['go']['main']['App']['GetHostSchema'](arg1);
}

export function GetLocationSchema(arg1) {
  return window['go']['main']['App']['GetLocationSchema'](arg1);
}

export function GetNetworkDevices(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetNetworkDevices'](arg1, arg2, arg3);
}

export function GetPlugins(arg1, arg2) {
  return window['go']['main']['App']['GetPlugins'](arg1, arg2);
}

export function GetPoints(arg1, arg2) {
  return window['go']['main']['App']['GetPoints'](arg1, arg2);
}

export function EditNetwork(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EditNetwork'](arg1, arg2, arg3, arg4);
}

export function GetConnection(arg1) {
  return window['go']['main']['App']['GetConnection'](arg1);
}

export function GetHostNetworks(arg1) {
  return window['go']['main']['App']['GetHostNetworks'](arg1);
}

export function DeleteHost(arg1, arg2) {
  return window['go']['main']['App']['DeleteHost'](arg1, arg2);
}

export function EditHostNetwork(arg1, arg2, arg3) {
  return window['go']['main']['App']['EditHostNetwork'](arg1, arg2, arg3);
}

export function GetHost(arg1, arg2) {
  return window['go']['main']['App']['GetHost'](arg1, arg2);
}

export function GetHostNetwork(arg1, arg2) {
  return window['go']['main']['App']['GetHostNetwork'](arg1, arg2);
}

export function GetLocationTableSchema(arg1) {
  return window['go']['main']['App']['GetLocationTableSchema'](arg1);
}

export function GetPcTime() {
  return window['go']['main']['App']['GetPcTime']();
}

export function GetBackup(arg1) {
  return window['go']['main']['App']['GetBackup'](arg1);
}

export function GetBackupsNoData() {
  return window['go']['main']['App']['GetBackupsNoData']();
}

export function GetConnectionSchema() {
  return window['go']['main']['App']['GetConnectionSchema']();
}

export function GetHostActiveNetworks(arg1, arg2) {
  return window['go']['main']['App']['GetHostActiveNetworks'](arg1, arg2);
}

export function GetLogsByConnection(arg1) {
  return window['go']['main']['App']['GetLogsByConnection'](arg1);
}

export function AddConnection(arg1) {
  return window['go']['main']['App']['AddConnection'](arg1);
}

export function BacnetWhois(arg1, arg2, arg3) {
  return window['go']['main']['App']['BacnetWhois'](arg1, arg2, arg3);
}

export function DeleteDevice(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteDevice'](arg1, arg2, arg3);
}

export function GetPcGetNetworks() {
  return window['go']['main']['App']['GetPcGetNetworks']();
}

export function GetPointsForDevice(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetPointsForDevice'](arg1, arg2, arg3);
}

export function PingRubixAssist(arg1) {
  return window['go']['main']['App']['PingRubixAssist'](arg1);
}
