// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLocationSchema(arg1) {
  return window['go']['main']['App']['GetLocationSchema'](arg1);
}

export function GetProducers(arg1, arg2) {
  return window['go']['main']['App']['GetProducers'](arg1, arg2);
}

export function DeleteConnectionBulk(arg1) {
  return window['go']['main']['App']['DeleteConnectionBulk'](arg1);
}

export function EditDevice(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EditDevice'](arg1, arg2, arg3, arg4);
}

export function EnablePluginBulk(arg1, arg2, arg3) {
  return window['go']['main']['App']['EnablePluginBulk'](arg1, arg2, arg3);
}

export function GetPointsForDevice(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetPointsForDevice'](arg1, arg2, arg3);
}

export function DeleteNetwork(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteNetwork'](arg1, arg2, arg3);
}

export function EditNetwork(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EditNetwork'](arg1, arg2, arg3, arg4);
}

export function GetConsumerClones(arg1, arg2) {
  return window['go']['main']['App']['GetConsumerClones'](arg1, arg2);
}

export function DeleteHostNetworkBulk(arg1, arg2) {
  return window['go']['main']['App']['DeleteHostNetworkBulk'](arg1, arg2);
}

export function GetConsumers(arg1, arg2) {
  return window['go']['main']['App']['GetConsumers'](arg1, arg2);
}

export function GetConsumer(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetConsumer'](arg1, arg2, arg3);
}

export function GetFlowDeviceSchema(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetFlowDeviceSchema'](arg1, arg2, arg3);
}

export function GetLocations(arg1) {
  return window['go']['main']['App']['GetLocations'](arg1);
}

export function GetNetworks(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetNetworks'](arg1, arg2, arg3);
}

export function DeletePoint(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeletePoint'](arg1, arg2, arg3);
}

export function DeletePointBulk(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeletePointBulk'](arg1, arg2, arg3);
}

export function GetBacnetDevicePoints(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetBacnetDevicePoints'](arg1, arg2, arg3, arg4, arg5);
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function WiresBackup(arg1, arg2, arg3) {
  return window['go']['main']['App']['WiresBackup'](arg1, arg2, arg3);
}

export function GetFlowPointSchema(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetFlowPointSchema'](arg1, arg2, arg3);
}

export function GetNetwork(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetNetwork'](arg1, arg2, arg3, arg4);
}

export function GetNetworkDevices(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetNetworkDevices'](arg1, arg2, arg3);
}

export function GetHost(arg1, arg2) {
  return window['go']['main']['App']['GetHost'](arg1, arg2);
}

export function GetHostActiveNetworks(arg1, arg2) {
  return window['go']['main']['App']['GetHostActiveNetworks'](arg1, arg2);
}

export function EditConsumer(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EditConsumer'](arg1, arg2, arg3, arg4);
}

export function GetScannerSchema() {
  return window['go']['main']['App']['GetScannerSchema']();
}

export function GetPluginByName(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetPluginByName'](arg1, arg2, arg3);
}

export function GitDownloadRelease(arg1, arg2) {
  return window['go']['main']['App']['GitDownloadRelease'](arg1, arg2);
}

export function StoreDownloadApp(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StoreDownloadApp'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateSettings(arg1, arg2) {
  return window['go']['main']['App']['UpdateSettings'](arg1, arg2);
}

export function DeleteDevice(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteDevice'](arg1, arg2, arg3);
}

export function DeleteHostNetwork(arg1, arg2) {
  return window['go']['main']['App']['DeleteHostNetwork'](arg1, arg2);
}

export function GetLogsWithData() {
  return window['go']['main']['App']['GetLogsWithData']();
}

export function GetPlugin(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetPlugin'](arg1, arg2, arg3);
}

export function DisablePlugin(arg1, arg2, arg3) {
  return window['go']['main']['App']['DisablePlugin'](arg1, arg2, arg3);
}

export function EditProducer(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EditProducer'](arg1, arg2, arg3, arg4);
}

export function GetFlowNetworkClone(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetFlowNetworkClone'](arg1, arg2, arg3, arg4);
}

export function GetPcGetNetworksSchema() {
  return window['go']['main']['App']['GetPcGetNetworksSchema']();
}

export function GetPluginsNames(arg1, arg2) {
  return window['go']['main']['App']['GetPluginsNames'](arg1, arg2);
}

export function GetReleaseByVersion(arg1) {
  return window['go']['main']['App']['GetReleaseByVersion'](arg1);
}

export function AddProducer(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddProducer'](arg1, arg2, arg3);
}

export function DeleteLogBulk(arg1) {
  return window['go']['main']['App']['DeleteLogBulk'](arg1);
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetServerNetworking(arg1) {
  return window['go']['main']['App']['GetServerNetworking'](arg1);
}

export function AddConnection(arg1) {
  return window['go']['main']['App']['AddConnection'](arg1);
}

export function GetFlowNetworkClones(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetFlowNetworkClones'](arg1, arg2, arg3);
}

export function GetNetworkSchema(arg1) {
  return window['go']['main']['App']['GetNetworkSchema'](arg1);
}

export function DeleteHostBulk(arg1, arg2) {
  return window['go']['main']['App']['DeleteHostBulk'](arg1, arg2);
}

export function GetStreamClones(arg1, arg2) {
  return window['go']['main']['App']['GetStreamClones'](arg1, arg2);
}

export function DeleteLocation(arg1, arg2) {
  return window['go']['main']['App']['DeleteLocation'](arg1, arg2);
}

export function DeleteNetworkBulk(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteNetworkBulk'](arg1, arg2, arg3);
}

export function GetFlowNetworks(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetFlowNetworks'](arg1, arg2, arg3);
}

export function AddPoint(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddPoint'](arg1, arg2, arg3);
}

export function EditHost(arg1, arg2, arg3) {
  return window['go']['main']['App']['EditHost'](arg1, arg2, arg3);
}

export function AddConsumer(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddConsumer'](arg1, arg2, arg3);
}

export function StoreDownloadAll(arg1, arg2, arg3) {
  return window['go']['main']['App']['StoreDownloadAll'](arg1, arg2, arg3);
}

export function GetHostInterfaces(arg1, arg2) {
  return window['go']['main']['App']['GetHostInterfaces'](arg1, arg2);
}

export function GetProducerClones(arg1, arg2) {
  return window['go']['main']['App']['GetProducerClones'](arg1, arg2);
}

export function AddStream(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddStream'](arg1, arg2, arg3);
}

export function DeleteConsumerBulk(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteConsumerBulk'](arg1, arg2, arg3);
}

export function EditStream(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EditStream'](arg1, arg2, arg3, arg4);
}

export function EditPoint(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EditPoint'](arg1, arg2, arg3, arg4);
}

export function ImportBackup(arg1) {
  return window['go']['main']['App']['ImportBackup'](arg1);
}

export function UpdateConnection(arg1, arg2) {
  return window['go']['main']['App']['UpdateConnection'](arg1, arg2);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DisablePluginBulk(arg1, arg2, arg3) {
  return window['go']['main']['App']['DisablePluginBulk'](arg1, arg2, arg3);
}

export function EditHostNetwork(arg1, arg2, arg3) {
  return window['go']['main']['App']['EditHostNetwork'](arg1, arg2, arg3);
}

export function GetLocationTableSchema(arg1) {
  return window['go']['main']['App']['GetLocationTableSchema'](arg1);
}

export function GetRelease(arg1) {
  return window['go']['main']['App']['GetRelease'](arg1);
}

export function OpenURL(arg1) {
  window['go']['main']['App']['OpenURL'](arg1);
}

export function PingHost(arg1, arg2) {
  return window['go']['main']['App']['PingHost'](arg1, arg2);
}

export function DeleteProducer(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteProducer'](arg1, arg2, arg3);
}

export function GetDevices(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetDevices'](arg1, arg2, arg3);
}

export function GetLocation(arg1, arg2) {
  return window['go']['main']['App']['GetLocation'](arg1, arg2);
}

export function BacnetWhois(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BacnetWhois'](arg1, arg2, arg3, arg4);
}

export function DeleteBackupBulk(arg1) {
  return window['go']['main']['App']['DeleteBackupBulk'](arg1);
}

export function GetFlowNetworkSchema(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetFlowNetworkSchema'](arg1, arg2, arg3);
}

export function GetNetworkByPluginName(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetNetworkByPluginName'](arg1, arg2, arg3, arg4);
}

export function GitListReleases(arg1) {
  return window['go']['main']['App']['GitListReleases'](arg1);
}

export function AddRelease(arg1, arg2) {
  return window['go']['main']['App']['AddRelease'](arg1, arg2);
}

export function EditFlowNetwork(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EditFlowNetwork'](arg1, arg2, arg3, arg4);
}

export function GetConnection(arg1) {
  return window['go']['main']['App']['GetConnection'](arg1);
}

export function GetHostNetworks(arg1) {
  return window['go']['main']['App']['GetHostNetworks'](arg1);
}

export function AddNetwork(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddNetwork'](arg1, arg2, arg3);
}

export function DeleteProducerBulk(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteProducerBulk'](arg1, arg2, arg3);
}

export function GetBackupsNoData() {
  return window['go']['main']['App']['GetBackupsNoData']();
}

export function DeleteConsumer(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteConsumer'](arg1, arg2, arg3);
}

export function GetPoints(arg1, arg2) {
  return window['go']['main']['App']['GetPoints'](arg1, arg2);
}

export function GetHosts(arg1) {
  return window['go']['main']['App']['GetHosts'](arg1);
}

export function GetNetworksWithPoints(arg1, arg2) {
  return window['go']['main']['App']['GetNetworksWithPoints'](arg1, arg2);
}

export function GetPcInterfaces() {
  return window['go']['main']['App']['GetPcInterfaces']();
}

export function GetServerTime(arg1) {
  return window['go']['main']['App']['GetServerTime'](arg1);
}

export function DoBackup(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['DoBackup'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetBackup(arg1) {
  return window['go']['main']['App']['GetBackup'](arg1);
}

export function GetBackups() {
  return window['go']['main']['App']['GetBackups']();
}

export function GetHostTime(arg1, arg2) {
  return window['go']['main']['App']['GetHostTime'](arg1, arg2);
}

export function DeleteDeviceBulk(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteDeviceBulk'](arg1, arg2, arg3);
}

export function DeleteStream(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteStream'](arg1, arg2, arg3);
}

export function GetConnections() {
  return window['go']['main']['App']['GetConnections']();
}

export function DeleteFlowNetwork(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteFlowNetwork'](arg1, arg2, arg3);
}

export function GetLogsByConnection(arg1) {
  return window['go']['main']['App']['GetLogsByConnection'](arg1);
}

export function UpdateLocation(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateLocation'](arg1, arg2, arg3);
}

export function GetProducer(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetProducer'](arg1, arg2, arg3);
}

export function AddHost(arg1, arg2) {
  return window['go']['main']['App']['AddHost'](arg1, arg2);
}

export function DeleteBackup(arg1) {
  return window['go']['main']['App']['DeleteBackup'](arg1);
}

export function DeleteFlowNetworkCloneBulk(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteFlowNetworkCloneBulk'](arg1, arg2, arg3);
}

export function GetHostInternetIP(arg1, arg2) {
  return window['go']['main']['App']['GetHostInternetIP'](arg1, arg2);
}

export function GetHostSchema(arg1) {
  return window['go']['main']['App']['GetHostSchema'](arg1);
}

export function AddDevice(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddDevice'](arg1, arg2, arg3);
}

export function GetConnectionSchema() {
  return window['go']['main']['App']['GetConnectionSchema']();
}

export function GetFlowNetwork(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetFlowNetwork'](arg1, arg2, arg3, arg4);
}

export function DeleteHost(arg1, arg2) {
  return window['go']['main']['App']['DeleteHost'](arg1, arg2);
}

export function DeleteLocationBulk(arg1, arg2) {
  return window['go']['main']['App']['DeleteLocationBulk'](arg1, arg2);
}

export function DeleteStreamBulk(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteStreamBulk'](arg1, arg2, arg3);
}

export function GetGitToken(arg1, arg2) {
  return window['go']['main']['App']['GetGitToken'](arg1, arg2);
}

export function GetReleases() {
  return window['go']['main']['App']['GetReleases']();
}

export function AddHostNetwork(arg1, arg2) {
  return window['go']['main']['App']['AddHostNetwork'](arg1, arg2);
}

export function DeleteAllConnections() {
  return window['go']['main']['App']['DeleteAllConnections']();
}

export function DeleteFlowNetworkClone(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteFlowNetworkClone'](arg1, arg2, arg3);
}

export function PingRubixAssist(arg1) {
  return window['go']['main']['App']['PingRubixAssist'](arg1);
}

export function GetPlugins(arg1, arg2) {
  return window['go']['main']['App']['GetPlugins'](arg1, arg2);
}

export function GetStreams(arg1, arg2) {
  return window['go']['main']['App']['GetStreams'](arg1, arg2);
}

export function GetPcGetNetworks() {
  return window['go']['main']['App']['GetPcGetNetworks']();
}

export function GetStream(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetStream'](arg1, arg2, arg3);
}

export function ImportNetwork(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ImportNetwork'](arg1, arg2, arg3, arg4, arg5);
}

export function Scanner(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Scanner'](arg1, arg2, arg3, arg4);
}

export function WiresBackupRestore(arg1, arg2, arg3) {
  return window['go']['main']['App']['WiresBackupRestore'](arg1, arg2, arg3);
}

export function AddFlowNetwork(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddFlowNetwork'](arg1, arg2, arg3);
}

export function EnablePlugin(arg1, arg2, arg3) {
  return window['go']['main']['App']['EnablePlugin'](arg1, arg2, arg3);
}

export function GetHostNetwork(arg1, arg2) {
  return window['go']['main']['App']['GetHostNetwork'](arg1, arg2);
}

export function GetDevice(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetDevice'](arg1, arg2, arg3, arg4);
}

export function GetPcTime() {
  return window['go']['main']['App']['GetPcTime']();
}

export function GetPoint(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetPoint'](arg1, arg2, arg3);
}

export function HostRubixScan(arg1, arg2) {
  return window['go']['main']['App']['HostRubixScan'](arg1, arg2);
}

export function AddLocation(arg1, arg2) {
  return window['go']['main']['App']['AddLocation'](arg1, arg2);
}

export function DeleteFlowNetworkBulk(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteFlowNetworkBulk'](arg1, arg2, arg3);
}

export function GetBackupsByApplication(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetBackupsByApplication'](arg1, arg2, arg3);
}
