// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHostNetwork(arg1) {
  return window['go']['main']['App']['AddHostNetwork'](arg1);
}

export function DeleteHost(arg1) {
  return window['go']['main']['App']['DeleteHost'](arg1);
}

export function EditHost(arg1, arg2) {
  return window['go']['main']['App']['EditHost'](arg1, arg2);
}

export function EditHostNetwork(arg1, arg2) {
  return window['go']['main']['App']['EditHostNetwork'](arg1, arg2);
}

export function GetHostNetworks() {
  return window['go']['main']['App']['GetHostNetworks']();
}

export function GetHosts() {
  return window['go']['main']['App']['GetHosts']();
}

export function AddHost(arg1) {
  return window['go']['main']['App']['AddHost'](arg1);
}

export function DeleteHostNetwork(arg1) {
  return window['go']['main']['App']['DeleteHostNetwork'](arg1);
}

export function GetHost(arg1) {
  return window['go']['main']['App']['GetHost'](arg1);
}

export function GetHostNetwork(arg1) {
  return window['go']['main']['App']['GetHostNetwork'](arg1);
}
