// Code generated by "stringer -type=Type"; DO NOT EDIT.

package store

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FlowFramework-0]
	_ = x[RubixWires-1]
}

const _Type_name = "FlowFrameworkRubixWires"

var _Type_index = [...]uint8{0, 13, 23}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
