// Code generated by "stringer -type=FunctionType"; DO NOT EDIT.

package logstore

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Connection-0]
	_ = x[Location-1]
	_ = x[Network-2]
	_ = x[Device-3]
}

const _FunctionType_name = "ConnectionLocationNetworkDevice"

var _FunctionType_index = [...]uint8{0, 10, 18, 25, 31}

func (i FunctionType) String() string {
	if i < 0 || i >= FunctionType(len(_FunctionType_index)-1) {
		return "FunctionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FunctionType_name[_FunctionType_index[i]:_FunctionType_index[i+1]]
}
