// Code generated by "stringer -type=TaskType"; DO NOT EDIT.

package logstore

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Create-0]
	_ = x[Delete-1]
	_ = x[Update-2]
	_ = x[BackUp-3]
	_ = x[Restore-4]
}

const _TaskType_name = "CreateDeleteUpdateBackUpRestore"

var _TaskType_index = [...]uint8{0, 6, 12, 18, 24, 31}

func (i TaskType) String() string {
	if i < 0 || i >= TaskType(len(_TaskType_index)-1) {
		return "TaskType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TaskType_name[_TaskType_index[i]:_TaskType_index[i+1]]
}
