// Code generated by "stringer -type=ApplicationType"; DO NOT EDIT.

package logstore

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RubixWires-0]
	_ = x[FlowFramework-1]
}

const _ApplicationType_name = "RubixWiresFlowFramework"

var _ApplicationType_index = [...]uint8{0, 10, 23}

func (i ApplicationType) String() string {
	if i < 0 || i >= ApplicationType(len(_ApplicationType_index)-1) {
		return "ApplicationType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ApplicationType_name[_ApplicationType_index[i]:_ApplicationType_index[i+1]]
}
