// Code generated by "stringer -type=SubApplicationType"; DO NOT EDIT.

package logstore

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FlowFrameworkNetwork-0]
	_ = x[FlowFrameworkDevice-1]
	_ = x[FlowFrameworkPoint-2]
	_ = x[FlowFrameworkFlowNetwork-3]
	_ = x[FlowFrameworkFlowNetworkClone-4]
	_ = x[WiresFlow-5]
	_ = x[Plugins-6]
	_ = x[Apps-7]
	_ = x[AppsStore-8]
}

const _SubApplicationType_name = "FlowFrameworkNetworkFlowFrameworkDeviceFlowFrameworkPointFlowFrameworkFlowNetworkFlowFrameworkFlowNetworkCloneWiresFlowPluginsAppsAppsStore"

var _SubApplicationType_index = [...]uint8{0, 20, 39, 57, 81, 110, 119, 126, 130, 139}

func (i SubApplicationType) String() string {
	if i < 0 || i >= SubApplicationType(len(_SubApplicationType_index)-1) {
		return "SubApplicationType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SubApplicationType_name[_SubApplicationType_index[i]:_SubApplicationType_index[i+1]]
}
